zhandlersocket.lo: /home/vbolshov/PhpstormProjects/zhandlersocket/ext/zhandlersocket.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/vbolshov/PhpstormProjects/zhandlersocket/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/vbolshov/PhpstormProjects/zhandlersocket/ext/zhandlersocket.c -o zhandlersocket.lo 
kernel/main.lo: /home/vbolshov/PhpstormProjects/zhandlersocket/ext/kernel/main.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/vbolshov/PhpstormProjects/zhandlersocket/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/vbolshov/PhpstormProjects/zhandlersocket/ext/kernel/main.c -o kernel/main.lo 
kernel/memory.lo: /home/vbolshov/PhpstormProjects/zhandlersocket/ext/kernel/memory.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/vbolshov/PhpstormProjects/zhandlersocket/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/vbolshov/PhpstormProjects/zhandlersocket/ext/kernel/memory.c -o kernel/memory.lo 
kernel/exception.lo: /home/vbolshov/PhpstormProjects/zhandlersocket/ext/kernel/exception.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/vbolshov/PhpstormProjects/zhandlersocket/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/vbolshov/PhpstormProjects/zhandlersocket/ext/kernel/exception.c -o kernel/exception.lo 
kernel/hash.lo: /home/vbolshov/PhpstormProjects/zhandlersocket/ext/kernel/hash.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/vbolshov/PhpstormProjects/zhandlersocket/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/vbolshov/PhpstormProjects/zhandlersocket/ext/kernel/hash.c -o kernel/hash.lo 
kernel/debug.lo: /home/vbolshov/PhpstormProjects/zhandlersocket/ext/kernel/debug.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/vbolshov/PhpstormProjects/zhandlersocket/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/vbolshov/PhpstormProjects/zhandlersocket/ext/kernel/debug.c -o kernel/debug.lo 
kernel/backtrace.lo: /home/vbolshov/PhpstormProjects/zhandlersocket/ext/kernel/backtrace.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/vbolshov/PhpstormProjects/zhandlersocket/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/vbolshov/PhpstormProjects/zhandlersocket/ext/kernel/backtrace.c -o kernel/backtrace.lo 
kernel/object.lo: /home/vbolshov/PhpstormProjects/zhandlersocket/ext/kernel/object.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/vbolshov/PhpstormProjects/zhandlersocket/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/vbolshov/PhpstormProjects/zhandlersocket/ext/kernel/object.c -o kernel/object.lo 
kernel/array.lo: /home/vbolshov/PhpstormProjects/zhandlersocket/ext/kernel/array.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/vbolshov/PhpstormProjects/zhandlersocket/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/vbolshov/PhpstormProjects/zhandlersocket/ext/kernel/array.c -o kernel/array.lo 
kernel/extended/array.lo: /home/vbolshov/PhpstormProjects/zhandlersocket/ext/kernel/extended/array.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/vbolshov/PhpstormProjects/zhandlersocket/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/vbolshov/PhpstormProjects/zhandlersocket/ext/kernel/extended/array.c -o kernel/extended/array.lo 
kernel/string.lo: /home/vbolshov/PhpstormProjects/zhandlersocket/ext/kernel/string.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/vbolshov/PhpstormProjects/zhandlersocket/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/vbolshov/PhpstormProjects/zhandlersocket/ext/kernel/string.c -o kernel/string.lo 
kernel/fcall.lo: /home/vbolshov/PhpstormProjects/zhandlersocket/ext/kernel/fcall.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/vbolshov/PhpstormProjects/zhandlersocket/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/vbolshov/PhpstormProjects/zhandlersocket/ext/kernel/fcall.c -o kernel/fcall.lo 
kernel/extended/fcall.lo: /home/vbolshov/PhpstormProjects/zhandlersocket/ext/kernel/extended/fcall.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/vbolshov/PhpstormProjects/zhandlersocket/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/vbolshov/PhpstormProjects/zhandlersocket/ext/kernel/extended/fcall.c -o kernel/extended/fcall.lo 
kernel/require.lo: /home/vbolshov/PhpstormProjects/zhandlersocket/ext/kernel/require.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/vbolshov/PhpstormProjects/zhandlersocket/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/vbolshov/PhpstormProjects/zhandlersocket/ext/kernel/require.c -o kernel/require.lo 
kernel/file.lo: /home/vbolshov/PhpstormProjects/zhandlersocket/ext/kernel/file.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/vbolshov/PhpstormProjects/zhandlersocket/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/vbolshov/PhpstormProjects/zhandlersocket/ext/kernel/file.c -o kernel/file.lo 
kernel/operators.lo: /home/vbolshov/PhpstormProjects/zhandlersocket/ext/kernel/operators.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/vbolshov/PhpstormProjects/zhandlersocket/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/vbolshov/PhpstormProjects/zhandlersocket/ext/kernel/operators.c -o kernel/operators.lo 
kernel/math.lo: /home/vbolshov/PhpstormProjects/zhandlersocket/ext/kernel/math.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/vbolshov/PhpstormProjects/zhandlersocket/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/vbolshov/PhpstormProjects/zhandlersocket/ext/kernel/math.c -o kernel/math.lo 
kernel/concat.lo: /home/vbolshov/PhpstormProjects/zhandlersocket/ext/kernel/concat.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/vbolshov/PhpstormProjects/zhandlersocket/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/vbolshov/PhpstormProjects/zhandlersocket/ext/kernel/concat.c -o kernel/concat.lo 
kernel/variables.lo: /home/vbolshov/PhpstormProjects/zhandlersocket/ext/kernel/variables.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/vbolshov/PhpstormProjects/zhandlersocket/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/vbolshov/PhpstormProjects/zhandlersocket/ext/kernel/variables.c -o kernel/variables.lo 
kernel/filter.lo: /home/vbolshov/PhpstormProjects/zhandlersocket/ext/kernel/filter.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/vbolshov/PhpstormProjects/zhandlersocket/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/vbolshov/PhpstormProjects/zhandlersocket/ext/kernel/filter.c -o kernel/filter.lo 
kernel/iterator.lo: /home/vbolshov/PhpstormProjects/zhandlersocket/ext/kernel/iterator.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/vbolshov/PhpstormProjects/zhandlersocket/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/vbolshov/PhpstormProjects/zhandlersocket/ext/kernel/iterator.c -o kernel/iterator.lo 
kernel/time.lo: /home/vbolshov/PhpstormProjects/zhandlersocket/ext/kernel/time.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/vbolshov/PhpstormProjects/zhandlersocket/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/vbolshov/PhpstormProjects/zhandlersocket/ext/kernel/time.c -o kernel/time.lo 
kernel/exit.lo: /home/vbolshov/PhpstormProjects/zhandlersocket/ext/kernel/exit.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/vbolshov/PhpstormProjects/zhandlersocket/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/vbolshov/PhpstormProjects/zhandlersocket/ext/kernel/exit.c -o kernel/exit.lo 
zhandlersocket/zexception.lo: /home/vbolshov/PhpstormProjects/zhandlersocket/ext/zhandlersocket/zexception.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/vbolshov/PhpstormProjects/zhandlersocket/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/vbolshov/PhpstormProjects/zhandlersocket/ext/zhandlersocket/zexception.zep.c -o zhandlersocket/zexception.lo 
zhandlersocket/logger.lo: /home/vbolshov/PhpstormProjects/zhandlersocket/ext/zhandlersocket/logger.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/vbolshov/PhpstormProjects/zhandlersocket/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/vbolshov/PhpstormProjects/zhandlersocket/ext/zhandlersocket/logger.zep.c -o zhandlersocket/logger.lo 
zhandlersocket/client.lo: /home/vbolshov/PhpstormProjects/zhandlersocket/ext/zhandlersocket/client.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/vbolshov/PhpstormProjects/zhandlersocket/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/vbolshov/PhpstormProjects/zhandlersocket/ext/zhandlersocket/client.zep.c -o zhandlersocket/client.lo 
zhandlersocket/command.lo: /home/vbolshov/PhpstormProjects/zhandlersocket/ext/zhandlersocket/command.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/vbolshov/PhpstormProjects/zhandlersocket/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/vbolshov/PhpstormProjects/zhandlersocket/ext/zhandlersocket/command.zep.c -o zhandlersocket/command.lo 
zhandlersocket/communicationexception.lo: /home/vbolshov/PhpstormProjects/zhandlersocket/ext/zhandlersocket/communicationexception.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/vbolshov/PhpstormProjects/zhandlersocket/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/vbolshov/PhpstormProjects/zhandlersocket/ext/zhandlersocket/communicationexception.zep.c -o zhandlersocket/communicationexception.lo 
zhandlersocket/connection.lo: /home/vbolshov/PhpstormProjects/zhandlersocket/ext/zhandlersocket/connection.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/vbolshov/PhpstormProjects/zhandlersocket/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/vbolshov/PhpstormProjects/zhandlersocket/ext/zhandlersocket/connection.zep.c -o zhandlersocket/connection.lo 
zhandlersocket/connectionexception.lo: /home/vbolshov/PhpstormProjects/zhandlersocket/ext/zhandlersocket/connectionexception.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/vbolshov/PhpstormProjects/zhandlersocket/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/vbolshov/PhpstormProjects/zhandlersocket/ext/zhandlersocket/connectionexception.zep.c -o zhandlersocket/connectionexception.lo 
zhandlersocket/debuglogger.lo: /home/vbolshov/PhpstormProjects/zhandlersocket/ext/zhandlersocket/debuglogger.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/vbolshov/PhpstormProjects/zhandlersocket/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/vbolshov/PhpstormProjects/zhandlersocket/ext/zhandlersocket/debuglogger.zep.c -o zhandlersocket/debuglogger.lo 
zhandlersocket/duplicateentryexception.lo: /home/vbolshov/PhpstormProjects/zhandlersocket/ext/zhandlersocket/duplicateentryexception.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/vbolshov/PhpstormProjects/zhandlersocket/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/vbolshov/PhpstormProjects/zhandlersocket/ext/zhandlersocket/duplicateentryexception.zep.c -o zhandlersocket/duplicateentryexception.lo 
zhandlersocket/encoder.lo: /home/vbolshov/PhpstormProjects/zhandlersocket/ext/zhandlersocket/encoder.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/vbolshov/PhpstormProjects/zhandlersocket/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/vbolshov/PhpstormProjects/zhandlersocket/ext/zhandlersocket/encoder.zep.c -o zhandlersocket/encoder.lo 
zhandlersocket/index.lo: /home/vbolshov/PhpstormProjects/zhandlersocket/ext/zhandlersocket/index.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/vbolshov/PhpstormProjects/zhandlersocket/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/vbolshov/PhpstormProjects/zhandlersocket/ext/zhandlersocket/index.zep.c -o zhandlersocket/index.lo 
zhandlersocket/log.lo: /home/vbolshov/PhpstormProjects/zhandlersocket/ext/zhandlersocket/log.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/vbolshov/PhpstormProjects/zhandlersocket/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/vbolshov/PhpstormProjects/zhandlersocket/ext/zhandlersocket/log.zep.c -o zhandlersocket/log.lo 
zhandlersocket/nulllogger.lo: /home/vbolshov/PhpstormProjects/zhandlersocket/ext/zhandlersocket/nulllogger.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/vbolshov/PhpstormProjects/zhandlersocket/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/vbolshov/PhpstormProjects/zhandlersocket/ext/zhandlersocket/nulllogger.zep.c -o zhandlersocket/nulllogger.lo 
zhandlersocket/whereclause.lo: /home/vbolshov/PhpstormProjects/zhandlersocket/ext/zhandlersocket/whereclause.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/vbolshov/PhpstormProjects/zhandlersocket/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/vbolshov/PhpstormProjects/zhandlersocket/ext/zhandlersocket/whereclause.zep.c -o zhandlersocket/whereclause.lo 
zhandlersocket/whereclausefilter.lo: /home/vbolshov/PhpstormProjects/zhandlersocket/ext/zhandlersocket/whereclausefilter.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/vbolshov/PhpstormProjects/zhandlersocket/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/vbolshov/PhpstormProjects/zhandlersocket/ext/zhandlersocket/whereclausefilter.zep.c -o zhandlersocket/whereclausefilter.lo 
$(phplibdir)/zhandlersocket.la: ./zhandlersocket.la
	$(LIBTOOL) --mode=install cp ./zhandlersocket.la $(phplibdir)

./zhandlersocket.la: $(shared_objects_zhandlersocket) $(ZHANDLERSOCKET_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_zhandlersocket) $(ZHANDLERSOCKET_SHARED_LIBADD)

